# Generated by Django 4.1.2 on 2022-10-10 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_studentposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
    ]
